В следующий раз не забуду делать коммиты, готово
htmlacademy-javascript/2404401-kekstagram-30 pull request #3
Opened 2023-10-16 21:30 UTC by beezlesusOK

2023-10-16 22:55 UTC, slavkapiyavka requested changes

2023-10-16 22:55 UTC, slavkapiyavka commented on js/main.js
1. именование переменных:

> const COMMENTS_NAME - хорошо,
> const result - плохо

2. обсудим форматирование на созвоне %)

2023-10-16 22:55 UTC, slavkapiyavka commented on js/main.js
> +const result = [];
подобные константы должны "проживать", то есть объявляться и использоваться по месту, а именно result - в createObjectCard

2023-10-16 22:55 UTC, slavkapiyavka commented on js/main.js
> +function createObjectCard() {
1. функция должна вернуть объект (правда по названию я не понимаю что за карточка объект, а по структуре догадываюсь что это описание фотографии). сейчас она возвращает undefined
2. по названию должно быть понятно что функция делает - генерирует описание поста

2023-10-16 22:55 UTC, slavkapiyavka commented on js/main.js
> +function createObjId(min, max) {
вот, а тут уже функция возвращает результат выполнения, это верно!
осталось только:
1. использовать эту функцию через замыкание
2. для успешного применения через замыкание перенести ARRAY_ID внутрь
3. и чуть иначе назвать функцию, потому что она генерирует случайное число / идентификатор. правильное имя позволит сделать функцию независимой , исходя из названия понимать что она делает, а так же использовать её где потребуется случайное число

2023-10-16 22:55 UTC, slavkapiyavka commented on js/main.js
> +function createObjUrl(min, max) {
эта функция точно лишняя. загляни в задание - там указана строка photos/{{i}}.jpg

вот на месте i вызови функцию получения случайного числа прям в функции генерации постов и ты получишь нужный результат. используй шаблонные строки

2023-10-16 22:55 UTC, slavkapiyavka commented on js/main.js
> +function createObjDescription(min, max) {
тоже не нужна эта функция - используй getRandomNumber вместе с массивом DESCRIPTION

2023-10-16 22:55 UTC, slavkapiyavka commented on js/main.js
> +function createObjLikes(min, max) {
и тут тоже не нужная функция - вместо неё зови getRandomNumber

2023-10-16 22:55 UTC, slavkapiyavka commented on js/main.js
> +  function getAvatarNumber() {
не нужна, используй getRandomNumber

2023-10-16 22:55 UTC, slavkapiyavka commented on js/main.js
> +    return COMMENTS_MESSAGE[getRandomNumber(0, COMMENTS_MESSAGE.length - 1)];
вот! перенеси этот результат и ниже в функцию генерации постов/комментов

2023-10-16 22:55 UTC, slavkapiyavka commented on js/main.js
> +for (let i = 0; i < 25; i++) {
[Array.from](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from) твой бро в этом и других случаях. он ещё пригодится тебе пару раз в этом файле

2023-10-19 07:53 UTC, beezlesusOK commented on js/main.js
> +function createObjectCard() {
В "описании поста" есть описание описание назвать "описание описания"?

2023-10-19 07:55 UTC, beezlesusOK commented on js/main.js
> +const result = [];
Объектная карточка. Ведь этот объект это данные поста в кексограмме, 25 постов или же 25 карт

2023-10-19 08:14 UTC, beezlesusOK commented on js/main.js
> +function createObjUrl(min, max) {
Писал функцию отдельно для того чтобы фотки не повторялись, подумал хоть нет в задании это будет лучше выглядеть, да и вообще кучу функций написал именно за этим, для более привлекательного вида, чтобы можно было менять в отдельности, но не подумал с какой целью это пишем, а именно для тестирования, судя по описанию задания и наверное это все не так важно

2023-10-19 08:16 UTC, beezlesusOK commented on js/main.js
> +function createObjectCard() {
Пошел на компромисс, generatesPostsObject, надеюсь ок)

2023-10-19 14:21 UTC, slavkapiyavka requested changes

2023-10-19 14:21 UTC, slavkapiyavka commented on js/main.js
> +      name: COMMENTS_NAME[getRandomNumber(0, COMMENTS_MESSAGE.length - 1)],
бери длину массива COMMENTS_NAME вместо COMMENTS_MESSAGE

2023-10-19 14:21 UTC, slavkapiyavka commented on js/main.js
> +    description: DESCRIPTION[getRandomNumber(1,6)],
лучше придерживаться длины массива и передавать параметры в getRandomNumber так же, как в остальных участках кода - DESCRIPTION[0, DESCRIPTION.length - 1] - так у тебя не будет ошибки, если длина массива уменьшится

2023-10-19 16:58 UTC, merged